name: SonarQube Analysis

on:
  push:
    branches: [main]

jobs:
  sonar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run SonarQube scan
        run: mvn clean verify sonar:sonar "-Dsonar.projectKey=sonarqube-github-demo" "-Dsonar.host.url=https://3653-124-160-63-226.ngrok-free.app" "-Dsonar.token=${{ secrets.SONAR_TOKEN }}"
