name: SonarQube Analysis

on:
  push:
    branches: [main]

jobs:
  sonar:
    runs-on: ubuntu-latest

    services:
      sonarqube:
        image: sonarqube:community
        ports:
          - 9000:9000
        options: >-
          --user=1001
          --health-cmd="curl -f http://localhost:9000/api/system/health || exit 1"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=20

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Wait for SonarQube to be UP
        run: |
          echo "Waiting for SonarQube..."
          until curl -s http://localhost:9000/api/system/health | grep -q '"status":"UP"'; do
            sleep 5
          done

      - name: Mask token
        run: echo "::add-mask::${{ secrets.SONAR_TOKEN }}"

      - name: Run Sonar Scanner
        run: mvn clean verify sonar:sonar -Dsonar.projectKey=user-api-demo -Dsonar.host.url=http://localhost:9000 -Dsonar.token=${{ secrets.SONAR_TOKEN }}
